---
- name: restart ssh
  service: name=sshd state=restarted

- name: reload ufw
  service: name=ufw state=restarted

- name: restart firewalld
  service: name=firewalld state=restarted enabled=yes

- name: reboot system
  reboot:
