---
- name: Verify
  hosts: all

  tasks:
    - name: Check VirtualBox kernel module status
      command: /usr/lib/virtualbox/vboxdrv.sh status
      register: vboxdrv_status
      changed_when: False
  
    # - name: Verify that molecule is installed
    #   become: true
    #   become_user: "{{ jenkins_user | default(ansible_user) }}"
    #   command: which molecule
    #   register: debug_whoami
  
    # - name: debug
    #   debug:
    #     msg: "{{ debug_whoami }}"

    - name: VirtualBox module is loaded
      ansible.builtin.assert:
        that:
          - "('is loaded' not in vboxdrv_status.stdout) or ('are loaded' not in vboxdrv_status.stdout)"

    - name: Verify that vboxdrv service is loaded
      systemd:
        name: vboxdrv.service
        enabled: true
        state: started
      check_mode: true
      register: vboxdrv_service
      failed_when: vboxdrv_service is changed
